ci: add dispatch bct step (#1060)
- Add dispatch step to BCT workflow

diff --git a/.github/workflows/bct.yml b/.github/workflows/bct.yml
--- a/.github/workflows/bct.yml
+++ b/.github/workflows/bct.yml
@@ -7,16 +7,34 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event.issue.pull_request && contains(github.event.comment.body, 'Deploy Preview for') && contains(github.event.comment.body, 'ready!')
     steps:
-      - uses: actions/checkout@v3
-      - name: Extract repository name
-        id: repo_name
-        run: echo "::set-output name=repo::$(echo ${{ github.repository }} | cut -d'/' -f2)"
-      - run: echo "https://deploy-preview-${{ github.event.issue.number }}--${{ steps.repo_name.outputs.repo }}.netlify.app"
-      - name: Dump GitHub context
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: echo "$GITHUB_CONTEXT"
-      - name: Dump job context
-        env:
-          JOB_CONTEXT: ${{ toJson(job) }}
-        run: echo "$JOB_CONTEXT"
+      - uses: actions/checkout@v4
+      - name: Extract Netlify URL
+        id: netlify_url
+        run: |
+          repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
+          echo "::set-output name=url::https://deploy-preview-${{ github.event.issue.number }}--${repo_name}.netlify.app"
+      - name: Check PR author's privileges
+        run: |
+          response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.event.pull_request.user.login }}/permission")
+          permission=$(echo $response | jq -r '.permission')
+          if [[ "$permission" != "admin" && "$permission" != "write" ]]; then
+            echo "::error::The PR author does not have 'admin' or 'write' privileges."
+            exit 1
+          else
+            echo "The PR author has 'admin' or 'write' privileges."
+          fi
+      - name: Trigger Browser Compatibility Tests
+        uses: actions/github-script@v4
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            github.repos.createDispatchEvent({
+              owner: 'sendbird',
+              repo: 'qe-browser-compatibility',
+              event_type: 'bct-test-trigger',
+              client_payload: { 
+                prNumber: ${{ github.event.issue.number }},
+                repoName: '${{ github.repository }}',
+                uikit_url: '${{ steps.netlify_url.outputs.url }}'
+              }
+            })
